### ISSUE TITLE
Atualizar Forca

### ISSUE THREAD

**Issue by fellipe-araujo** [UnBParadigmas2021-1/2021.1_G2_Funcional_Forca#3]
## Descrição
* Atualização da forca.

## Tarefas
- [x] A forca deve ser atualizada depois de cada letra digitada pelo usuário;

## Critérios de Aceitação
- [ ] Caso o usuário acerte uma letra, ela deve ser incrementada na estrutura da palavra;
- [ ] Caso o usuário erre uma letra, uma parte do corpo deve ser adicionada.

**Comment by juniopereirab** [comment]
Deixei um print so pra testar a palavra. Pra ver o erro e o acerto etc.
