### ISSUE TITLE
Verificar Letra

### ISSUE THREAD

**Issue by fellipe-araujo** [UnBParadigmas2021-1/2021.1_G2_Funcional_Forca#4]
## Descrição
* Analisar a letra digitada.

## Tarefas
- [ ] Criar lógica para verificar se a letra digitada pelo usuário está presente na palavra original.

## Critérios de Aceitação
- [ ] Deve ser possível saber se a letra digitada está certa ou não.

**Comment by juniopereirab** [comment]
Acredito que essa parte já foi feita na issue #3, e no PR #7 pois pra verificar o acerto ou o erro. TInha que verificar a letra.
